site_name: Big Data · Graphs · Evolutionary · Cellular Automata — Classroom
site_description: Material educativo sobre Big Data, Teoría de Grafos, Algoritmos Evolutivos y Autómatas Celulares
site_author: Sergio Gevatschnaider
site_url: https://sgevatschnaider.github.io/BigData-Graphs-Evo-CA-Classroom/
repo_url: https://github.com/sgevatschnaider/BigData-Graphs-Evo-CA-Classroom
repo_name: BigData-Graphs-Evo-CA-Classroom

theme:
  name: material
  language: es
  features:
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Schedule: schedule.md
  - Modules:
      - Big Data: modules/01-bigdata.md
      - Graphs: modules/02-graphs.md
      - Evolutionary: modules/03-evolutionary.md
      - Cellular Automata: modules/04-cellular-automata.md
  - Notebooks:
      - Introducción a Big Data: notebooks/01_BigData_Intro.html
      - Fundamentos de Grafos: notebooks/02_Graphs_Fundamentals.html
      - Algoritmos Evolutivos: notebooks/03_Evolutionary_Algorithms.html
      - Autómatas Celulares: notebooks/04_Cellular_Automata.html

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
