[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bigdata-graphs-evo-ca-classroom"
version = "0.1.0"
description = "Teaching material for Big Data, Graphs, Evolutionary Algorithms, and Cellular Automata."
readme = { file = "README.md", "content-type" = "text/markdown" }
requires-python = ">=3.10"
authors = [{ name = "Sergio Gevatschnaider" }]
license = { file = "LICENSE" }
keywords = ["big data", "graphs", "networkx", "education", "notebooks"]

dependencies = [
    "numpy>=1.24,<2.1",
    "scipy>=1.10,<1.14",
    "pandas>=2.0,<2.3",
    "matplotlib>=3.7,<3.9",
    "networkx>=3.2,<4",
    "scikit-learn>=1.4,<1.6",
    "numba>=0.58,<0.60",
    "ipykernel>=6.29,<7"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["classroom*"]

[tool.black]
line-length = 88
target-version = ["py310"]
