name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Unit tests
        run: |
          pytest -q tests/test_ca.py tests/test_evo.py tests/test_graphs.py

      - name: Notebooks (nbmake)
        run: |
          pytest --nbmake -q notebooks/01_BigData_Intro.ipynb
          pytest --nbmake -q notebooks/02_Graphs_Fundamentals.ipynb
