name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: pip install -e .
      # Unit tests (sólo los 3 archivos, evitamos duplicar notebooks)
      - name: Unit tests
        run: pytest -q tests/test_ca.py tests/test_evo.py tests/test_graphs.py
      # Notebooks con nbmake (ejecución controlada)
      - name: Notebooks (nbmake)
        run: |
          pytest --nbmake -q notebooks/01_BigData_Intro.ipynb
          pytest --nbmake -q notebooks/02_Graphs_Fundamentals.ipynb

